default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_rails7_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: ajax_app_rails7_test

production:
  <<: *default
  adapter: postgresql
<<<<<<< Updated upstream
  url: <%= ENV['DATABASE_URL'] %>
=======
  url: <%= ENV['DATABASE_URL'] %>
>>>>>>> Stashed changes
